### ISSUE TITLE
Is there a README?

### ISSUE THREAD

**Issue by hsluoyz** [h4ckedneko/casbin-httpfs#1]

**Comment by h4ckedneko** [comment]
I will write a README and documentation before v1.

Last night, I started writing this adapter because we will use it in our project. Maybe before after our first deployment on that project I will release v1.

**Comment by hsluoyz** [comment]
Thanks! Already added to the list: https://github.com/casbin/casbin-website/commit/61e616a26e69786afea0b49ccecd665b1f185451

**Comment by h4ckedneko** [comment]
Thank you!

**Comment by hsluoyz** [comment]
@h4ckedneko any update?

**Comment by specter25** [comment]
@hsluoyz can i work on this issue ?

**Comment by h4ckedneko** [comment]
@hsluoyz I'm writing a README now and I will push it later. Sorry for the delay.

**Comment by h4ckedneko** [comment]
@hsluoyz The readme is now finished. I'll write tests tomorrow and release v1.

**Comment by hsluoyz** [comment]
Thanks to both of you!
